instamap:
  redirect_pattern: '{redirectUri}/'

instagram:
  user_uri: https://api.instagram.com/v1/users/{userId}/?access_token={accessToken}
  auth_uri: https://api.instagram.com/oauth/authorize/?client_id={clientId}&redirect_uri={redirectUri}&response_type=code
  access_token_uri: https://api.instagram.com/oauth/access_token
  client_id: d5a7f5922ff94028b89e0e31b0314e78